CREATE DATABASE systemcontrol;

CREATE TABLE user (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL,
	telephone VARCHAR(30) NOT NULL,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(80) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE stock (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_name VARCHAR(256) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  sale_price DECIMAL(10,2) NOT NULL,
  amount INT(11) NULL DEFAULT NULL,
  due_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE customers (
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    company VARCHAR(256) NOT NULL,
    email VARCHAR(50) NOT NULL,
    cnpj VARCHAR(20) NOT NULL,
    address VARCHAR(80) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);